name: Generate documentation
description: Generate all documentation

runs:
  using: composite
  steps:
    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: Install just
      shell: bash
      run: cargo install just
    - name: Install mdBook
      shell: bash
      run: cargo install mdbook
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
    - name: Build documentation
      shell: bash
      run: just build-docs
