#!/usr/bin/env python3
#
# A script to generate markdown documentation from table schemas.

from table2md import MarkdownTable
import yaml
from pathlib import Path

_DOCS_DIR = Path(__file__).parent
_SCHEMA_DIR = _DOCS_DIR.parent / "schemas" / "input"
_FILE_ORDER = {"Agents": ["agents"]}  # , "agent_*"]}


def generate_markdown() -> str:
    out = (
        "# Input file format\n"
        f"<!-- Automatically generated by {__name__}.py. Do not edit manually. -->\n"
        "<!-- markdownlint-disable MD013 -->\n\n"
    )

    for title, patterns in _FILE_ORDER.items():
        out += f"## {title}\n"

        for pattern in patterns:
            paths = map(str, _SCHEMA_DIR.glob(f"{pattern}.yaml"))
            for path in map(Path, sorted(paths)):
                out += process_file(path)

    return out


def process_file(path: Path) -> str:
    out = f"\n### `{path.stem}.csv`\n\n"
    with path.open() as f:
        data = yaml.load(f, Loader=yaml.Loader)

    out += f"{data['title']}. {data['description']}.\n\n"

    out += fields2table(data["fields"])

    return out


def fields2table(fields: list[dict[str, str]]) -> str:
    data = [
        {
            "Field": f"`{f['name']}`",
            "Title": f["title"],
            "Description": f.get("description", ""),
        }
        for f in fields
    ]
    return str(MarkdownTable.from_dicts(data))


if __name__ == "__main__":
    print(generate_markdown(), end="")
