name: Cargo Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build_and_test:
    name: Run tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            coverage: true
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo test --verbose

      - if: ${{ matrix.coverage }}
        uses: ./.github/actions/codecov
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
